### ISSUE TITLE
Triple repetition of species/genus in data

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#12]
In CS data we have the species/genus combination of fields for:
 - plant_population
 - plant_line, which a plant_population is related to
 - plant_variety, which a plant_line is related to
 - (perhaps more, not detected now).

The issue is to sort out if this is on purpose or should we re-normalize it and, for instance, leave the species/genus data only in the plant_variety table. If that is the case, solve the problem of having data discrepancy between these tables.

Consult @sarahcayling and @wjurkowski wrt that.

This is the first in the, probably long, series of data cleansing tasks.

**Comment by Nuanda** [comment]
Two further tables that might be related to that problem:
 - clone_libraries: has genus and species columns
 - probes: has species column.

However, clone_libraries is a de facto empty table.

**Comment by nowakowski** [comment]
The likely course of action would be to drop all occurrences of `species`, `genus` and `subtaxa` in the CropStoreDB data model and replace them with references to an ontology data table. This, however, entails fixing erroneous data in the current database. We are in the process of discussing this issue with TGAC.

**Comment by Nuanda** [comment]
@nowakowski We have dealt with that genus, species, subtaxa in Plant Lines. We are told to get rid of Plant Varieties and to connect PV Details, somehow, "directly" to PLs. Can we do that?

**Comment by nowakowski** [comment]
@Nuanda Yes, that can be done - however if the relation between PV and PVD is not strictly 1:1 then the resulting relation between PL and PVD would have to be many-to-many, which would require a linking table and therefore the model would not become any simpler. @wjurkowski - can a PlantVariety record have more than one PlantVarietyDetail record associated with it?

**Comment by nowakowski** [comment]
On closer inspection the relation between PV and PVD seems to be strictly 1:1, however there are relatively few PV records which have a PVD record attached (692 of 3261). Dropping PV and moving all of its relevant columns to PVD will result in a sparse table - tbh I do not see any upside (from the PoV of database optimization) as the existing model is not incorrect. @Nuanda - you said that "we are told to get rid of PlantVarieties" - is this a request coming from TGAC, and if so - could I inquire about the rationale?

**Comment by Nuanda** [comment]
@nowakowski I resent you the email from Sarah and Wiktor, where they propose that.

**Comment by nowakowski** [comment]
Since the issue involving contradictory `genus`, `species` and `subtaxa` fields is addressed by introducing `taxonomy_terms`, there does not seem to be a clear reason for dropping `plant_varieties`. Instead I propose the following:

- rename `plant_varieties` to `plant_line_details` and keep its content but drop `genus`, `species` and `subtaxa` (these fields are no longer needed since there is now a link between `plant_lines` and `taxonomy_terms`
- drop `plant_variety_detail` but merge all of its semantically meaningful fields into `plant_line_details`
- retain an optional 1:1 relation between `plant_lines` and `plant_line_details` - in this way `plant_line_details` becomes a repository of additional metadata concerning specific plant lines.

Opionions?

**Comment by Nuanda** [comment]
Sounds ok to me.
