### ISSUE TITLE
The assignment of map_locus_hits to map_positions is ambiguous

### ISSUE THREAD

**Issue by nowakowski** [eSpectrum-IT/brassica#120]
`map_locus_hits` contains a column named `map_position` - presumably the FK for `map_positions` (as pictured on the CropstoreDB entity relationship diagram); however `map_position` is not a prmary key in `map_positions` and its values are not unique in this table. As such, it is impossible to unambiguously assign each `map_locus_hits` record to a single `map_positions` record.

This is a crucial issue, suggesting a bug in the existing data model. Is there an algorithm which would enable us to decide which `map_positions` record to select for each `map_locus_hits` record? Perhaps this should became a many-to-many relationship, or perhaps the relationship should be dropped altogether?

**Comment by sarahcayling** [comment]
The map_position will be a coordinate on a linkage group, so you need to join the map_position to the linkage_group_id when looking at both tables. This must be why both of these fields are primary keys in both tables. Does this help? 

The linkage_group_id seems to be a composite (barring formatting diffs) between the linkage_map_id and the consensus_group_assignment.

**Comment by nowakowski** [comment]
@sarahcayling Thank you for looking into this issue. :) Unfortunately the problem goes deeper than that. Contrary to what you're proposing the aggregation `{map_position, linkage_group_id}` cannot be used as a candidate primary key in `map_positions` because it is not unique: many records - sometimes more than two dozen - share the same pairs of values.

In fact, `map_positions` does not have an obvious primary key at all - the uniqueness criterion is not satisfied even if you throw in `marker_assay_name` or `population_locus` (or both!).

If we did have a two-part primary key in `map_positions` the problem would disappear because each `map_locus_hits` can be unambiguously related to `linkage_groups` and therefore a single `map_position` record could be found for each `map_locus_hit`. Unfortunately, this is not presently the case.

The way things stand it seems that there are redundant records in `map_positions` but it is unclear which records can be kept and which ones should be discarded. Can you suggest a procedure which we could follow to ensure that only one record remains in the table for each `{map_position, linkage_group_id}` value pair?

**Comment by sarahcayling** [comment]
The way that the genetic maps are constructed, the mapping_locus ids get binned together, so therefore you can have multiple mapping_locus records for the same linkage_group + map_position combination. Biologically this is a limitation of genetic mapping, and completely normal :)

We had a look and if you use linkage_groups and mapping_locus together, you get unique mappings between map_locus_hits and map_positions tables. We checked out why adding the linkage_groups is necessary (as this seemed weird biologically) and this is due to inconsistent nomenclature with the linkage_map_ids - for instance mapping_locus Ra2G09 maps to 7 different linkage groups, derived from different populations/experiments/years but all with the same consensus_group_assignment of 'A01'. The consensus_group_assignment column could use some cleaning up from the examples we saw...

**Comment by nowakowski** [comment]
Superseded by #228 - closing.
