### ISSUE TITLE
Submissions: TaxonomyTerm select has different (browser default) style

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#259]
Spotted in FireFox, on Linux.

**Comment by Nuanda** [comment]
Same think, I guess, in IE11.

**Comment by bchucherko** [comment]
Select has native style depedning on browser - all other selects on the page use select2, that's why they differ. I suggest using select2 on taxonomy term as well, to keep styling & interaction cosistent.
Otherwise we would have to style (or via additional js library) simple select input, to make it consistent.

**Comment by Nuanda** [comment]
@kammerer Tomasz, do you know how to change that in submission forms?

**Comment by kammerer** [comment]
Using select2 as @bchucherko suggested is the easiest option, I can handle it.
