### ISSUE TITLE
Enable HTTP caching for browsing data

### ISSUE THREAD

**Issue by kammerer** [eSpectrum-IT/brassica#363]
Plant lines especially take quite a bit to load (a few seconds at least).

**Comment by kammerer** [comment]
Same for autocomplete.

**Comment by kammerer** [comment]
Not sure what's the problem but I only managed to make it work with cache-control max-age, and not with conditional get which would be more appropriate here.

**Comment by Nuanda** [comment]
Have you considered using sth like that for datatable json responses:

http://api.rubyonrails.org/classes/ActionController/ConditionalGet.html#method-i-fresh_when

together with simple nginx server cache and checking, for instance, if given model count is the same as it was (Model.count should be pretty fast)? Do you think this kind of scenario is possible at all?

**Comment by Nuanda** [comment]
Ok, after some tests I see there is not much to gain in nginx, since like 7/8 of the time is spent on pure download (it's a 3 MB document for all plant lines). So you are right that only client-side cache will help us here. Whether it is useful to tackle the server-side delay (that 1/8th of the TTFB wait) is questionable.

By the way same time is saved on rendering with deferRender: true flag in DataTables (already done).

**Comment by Nuanda** [comment]
Tomasz, can we do anything with the client-side cache for data tables content?
