### ISSUE TITLE
Provide curated Trait Ontology file, to be imported into BIP database

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#420]
The content of that should be in line with the decision taken in #419.

**Comment by Nuanda** [comment]
@teatree1212  See #391 for the beginning of this discussion. What I tarted to do is:
 1. create a new Trait table just for the vocabulary (or ontology) and make TraitDescriptors relate to this new table
 2. parse and save all non-obsolete TO terms there
 3. for each TD, either use your google docs file with mapping to TO, and relate that TD with the indicated Trait TO term (e.g. relate every TD that has descriptor_name == 'seed oil content' to TO:0000604)
 4. for TDs with no suitable TO detected, I create a new "non canonical" Trait entry and relate them to the new entry.

In the future, the Trait table (that includes TO trait names and Cropstore-originating trait names now) will be able to get the CO trait names as well. Or, for instance, the other names you propose in the "I" column of this file:

https://docs.google.com/spreadsheets/d/1VNq_BbZ8ieW8e-rjrTA5C7OcfpTcA3hOyNtZITu9TxM/edit#gid=1514310994

But that's for the future. TD stays, of course, as we need them for methods/materials description, plant part relation etc. etc. The new Trait table is only a vocabulary.

Now, I have a couple of question to the google doc:
 - Q1. I assume the green background means "name found in BIP under TraitDescriptor.descriptor_name column", right? (the legend does not explicitly say "green == BIP")
 - Q2. Cases like row number 11 ("oleic acid content") are difficult, as you name a TO term that identifies that certain trait (TO:0005002), and that term reads exactly "name: oleic acid content" in the TO.obo file, yet you propose to rename it to "Seed C18:1" - if we want to retain TO-consistency, we can't do that (as TO calls that certain trait "oleic acid content" and not "Seed C18:1"). Anyway, I do nothing with the "I" column at the moment, but this question is for the future consideration.

**Comment by teatree1212** [comment]
Q1: Correct. In "sheet 1" you see the colour legend, which I have now complemented with names.
Q2: I didn't know that this is convention. But if that is the case then better name it according to the existing TOrecord. In the far far future, we will most likely include the CropOntology terms in column "I" rather than Trait Ontology terms. CropOpntology makes more sense for our purposes.

**Comment by teatree1212** [comment]
we will other than in TO always have a plant part attached to a trait now. TO is not consistent in this regard but CropOntology is.

**Comment by Nuanda** [comment]
I understand rows 39 and 42 mean: replace all these terms with the one in column "I". However, shouldn't cell I42 read "leaf dry weight **plus** bag"?

**Comment by teatree1212** [comment]
you are correct. Thanks for pointing that out! I moved the "minus bag" terms to the appropriate rows, too.
Since we have decided to add the plant part to the trait,  I also had to tear apart my some traits again and added them on the bottom of the list. Sorry i did not think of this earlier!
changes are marked by the black boxes around them. everything should be up to dat now.
