### ISSUE TITLE
Add PlantVariety relation to PlantAccession

### ISSUE THREAD

**Issue by Nuanda** [eSpectrum-IT/brassica#500]
As decided in #481 - please add these two relations and make them mutually exclusive, i.e., no single PSU could be related to both a PL and a PV at the same time.

I'm not sure what to do with the current PSUs. I guess we can safely assign PL relation to those PSUs that have a PA relation and the related PA has a PL assigned.

How many PSUs would be left with no PL after that?

**Comment by teatree1212** [comment]
I received a document from Graham King about definitions of PLine and PVariety and how they act together. They further argue that Accessions are useful because PlantVariety names are error-prone. 
Please put this on hole for now,  have a look at this document and Wiktor and I will talk about how to proceed with the relation. I think Wiktor should decide whether we should diverge so much from the Schema, which would also give different meaning to PlantLine and PVariety compared to the CropStore meaning. Sending the email now.

**Comment by teatree1212** [comment]
Wiktor and I have just had a meeting. and have come to the conclusion to go via  an accession id and not changing the schema in order to directly connect to PlantLines or PlantVarieties. Instead, the user needs to make up an artificial accession. This still leaves the problem though, that , then, PlantLines an PlantAccessions both may have to be connected to Accessions.

**Comment by nowakowski** [comment]
May I inquire as to the reason behind this choice? Also, I'm having trouble interpreting the last sentence in your statement - currently a PlantAccession is linked to a specific PlantLine and a PlantLine may be linked to a specific PlantVariety. In what way would you like to see this changed?

If we are to "manufacture" artificial PlantAccession records, could you specify how to populate their attributes (specifically - plant_accession, plant_accession_derivation, accession_originator, originating_organisation, year_produced, date_harvested, female_parent_plant_id, male_parent_plant_id, entered_by_whom)?

**Comment by teatree1212** [comment]
Response to your first paragraph:  
Biologically and for Researchers it is very helpful to have information about Accessions if they exist ( but they don't always exist). In the document sent to eSprectrum, they argue that accessions need to be used to account for genetic drift. This concept of genetic drift is important for researchers when it comes to the reproducibility of their trait scores. Sometimes using the same line stored from different gene banks ( seed banks) to be grown under exactly the same conditions may render different results, because the "line" itself not necessarily is the purest genetical unit. 


as explanation about my last sentence:
in #481 we decided to link PSU directly to either PL and PV and kick out the Accessions. In that context, i also mentioned that trials sometimes deal with Lines or with Varieties, which means that sometimes  a PSU  (or if we keep Accession in between: an Accession)  needs to be directly linked to either of them.
As stated by @Nuanda earlier:
As decided in  #481 - please add these two relations and make them mutually exclusive, i.e., no single PSU could be related to both a PL and a PV at the same time.


Response to your second paragraph:
In a  perfect world  the  the "line" itself  would be the purest genetical unit or if that still wasn't the case, experimentalists would have all this information and it would be easy to submit.. But the database has to account for the more Chaotic components. In case of artificial Accessions, we will need to keep them empty. In case of real accessions, we need the submitter to add this information at some point somehow ..): Maybe after submission of the Trait Scores?

I personally think that the submission gets more and more complex and maybe there should be a trade- off between level of granularity and people not submitting anything..- and of course the value of the submission. Too little metadata will render the data without context and therefore unusable.

**Comment by wjurkowski** [comment]
Yes, the tables might be empty in some cases but I don't see the reason to adapt the schema in order to comply to someones suboptimal study design. We need Accessions for exp. reproducibility hence the current model linking lines with samples is ok. I don't see any other alternative. I hope the projects with incomplete data will be minority.

As far as the submission is concerned could all this information (line/variety,accession, acc.synonymes, exp. study design, traits) be downloaded in one go?

**Comment by teatree1212** [comment]
TBH, Don’t you think we should rely a bit on the organisation skills of the seed banks to host such information? I think the **Accession and the originating_organisation** could be enough. The experimentalists also just get the seeds and don't know themselves which female and male parental line has been crossed in order to produce those particular seeds.

**Comment by Nuanda** [comment]
Forgive me a side note, but I want to address the other @wjurkowski's question (about the download). Currently only in two goes. Explanation:
 - exp. study design, accession: PSU table (like: https://bip.tgac.ac.uk/data_tables?model=plant_scoring_units&query[plant_trials.id]=2)
 - line, trait, score: TS table (like: https://bip.tgac.ac.uk/data_tables?model=trait_scores&query[plant_scoring_units.id]=1397)
 - the new Scoring table (like: https://bip.tgac.ac.uk/trial_scorings/2) gives, as you remember, the 'pivot' scoring view.

If you wish to, we can add line/variety information to the PSU table. But the trait will be tricky, since there could be N scores (and, therefore, traits) per PSU. There are no acc. synonyms at the moment (see #392). All these tables could be downloaded in CSVs.

**Comment by Nuanda** [comment]
@teatree1212  @wjurkowski So, the conclusion seems to be to _always require_ "some kind" of accession info, per PSU (== per uploaded trait scoring table _row_), yes? We can put these two columns (`accession` and `originating_organisation`) in the trait scoring CSV template, and tell the user that the first one is obligatory, and the second one is not (or some other rule you want to apply).

Wiktor also mentioned that some RIPR scoring sheets include more complex set of accession identifiers (`nottingham_name`, `york_accession_name`, `york_accession_id`). I understand we will ask the user to decide which one is the most important, and copy that column under `accession` column header inside our template.

However, should we add another DB column called, for instance, `accession_synonyms`? And add such a column in the scoring template CSV, where users may put (an)other value(s), maybe comma-separated if more than one, which we will not parse or interpret in any way - just copy directly to the DB (and show in the Browse section tables)?

**Comment by teatree1212** [comment]
I have made changes to the template mentioned above 

sample_id now compulsory

Tissue/PlantPart , yes you are right. I did this together with some experimentalists and they wanted plant part there, but it is part of the trait, so not necessary actually.

Some sort of Accession will always be compulsory. Without an institution, it is however without interpretable value, which is why this also needs to be made compulsory.

I think using an optional acession_synonym this is a good compromise.

**Comment by teatree1212** [comment]
in response to your previous comment: adding line/variety information to the PSU table is a good start.

**Comment by Nuanda** [comment]
@teatree1212 Is it? I thought there are two viable, mutually exclusive options here:

 - we **require** accession information, have each submitted PSU related to an existing or a newly created PlantAccession, and to be related with either a PlantLine or a PlantVariety through that PAccession record
 - or we leave accession information optional, and in such a case, we need to have the option to relate each submitted PSU _directly_ with either a PLine or a PVariety.

In the first case we may need to add PAccession -> PVariety relation (since now there is only the PAccession ->PLine relation now, and, as I understand, not all experiments involve lines).

Only in the second case we should need direct PSU -> PL / PV relations. So, if we decided to have compulsory accession information (the first case) in the trait scoring CSV, then we no longer need to relate the PSU table to either PL or PV tables, right?

**Comment by teatree1212** [comment]
Correct. Go ahead with the first  option, as we make some accession information **required** ( both the accession and the accession_originator) that is all however and the rest of the table will most likely remain empty with our current approach- at least when using the wizard.

Is it possible to relate PlantLine and PlantVariety with each other, even though they both can be related to PAcession?

**Comment by Nuanda** [comment]
It is both possible and planned - otherwise we would not be able to link a PlantLine with a PlantVariety anymore (like we are able now). We will just add the new PlantAccession -> PlantVariety link (the other one, PlantAccession -> PlantLine is already there). To avoid chaos, we will make these two PA relations mutually exclusive - so a PlantAccession may be related to either a PL or a PV, but never to both at the same time.

**Comment by Nuanda** [comment]
@nowakowski Piotr, this is ready for implementation.

**Comment by Nuanda** [comment]
@teatree1212 Annemarie, I have one additional question to you regarding that. New we may have PAs which are related directly to PVs. PA table

https://bip.tgac.ac.uk/data_tables?model=plant_accessions

has the new column to show related varieties (of course, empty now). TraitScores table

https://bip.tgac.ac.uk/data_tables?model=trait_scores&query[plant_scoring_units.id]=1641

is another one that shows related (through two joins: PSU -> PA) PLs (the 'Line name' column).  Should we add here, as well, the alternative column 'Variety' (for scores which are related, through their PAs, with PVs rather than PLs), or maybe (for brevity) should we replace the current 'Line name' column with 'Plant accession' link (assuming the user will be able to find the relevant PL/PV there, one click away)?
